apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1-bigip
  namespace: simple-web-bigip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-v1-bigip
  template:
    metadata:
      labels:
        app: app-v1-bigip
    spec:
      containers:
      - name: app-v1-bigip
        image: nginxdemos/hello
        ports:
        - containerPort: 80
