apiVersion: cis.f5.com/v1
kind: Policy
metadata:
  labels:
    f5cr: "true"
  name: policy-web-bigip
  namespace: simple-web-bigip
spec:
  l7Policies:
    waf: /Common/WAF_Policy
  profiles:
    logProfiles:
      - /Common/Log all requests
