apiVersion: v1
kind: Service
metadata:
  name: app-v1-svc
  namespace: simple-web-bigip
  labels:
    app: app-v1-svc
spec:
  ports:
  - name: app-v1-svc
    port: 8080
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    app: app-v1-bigip
