apiVersion: v1
kind: Service
metadata:
  annotations:
    cis.f5.com/ipamLabel: Default
    cis.f5.com/health: '{"interval": 10, "timeout": 31}'
    cis.f5.com/policyName: policy-web-bigip
  name: app-v1-bigip-svc
  namespace: simple-web-bigip
  labels:
    app: app-v1-bigip-svc
spec:
  ports:
  - name: app-v1-bigip-svc
    port: 8080
    protocol: TCP
    targetPort: 80
  type: Loadbalancer
  selector:
    app: app-v1-bigip
