apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  namespace: xc-simple-k8s
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30050
    protocol: TCP
    name: http
  selector:
    app: coffee
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  namespace: xc-simple-k8s
  labels:
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30051
    protocol: TCP
    name: http
  selector:
    app: tea
  type: NodePort
