apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: policy-arcadia
  namespace: arcadia-simple-nginx
spec:
  waf:
    enable: true
    apPolicy: "secops/blocking-arcadia"
    securityLogs:
    - enable: true
      apLogConf : "secops/logconf-arcadia"
      logDest: "syslog:server=docker.de1chk1nd-lab.aws:515"
    - enable: true
      apLogConf : "secops/logconf-arcadia"
      logDest: "syslog:server=elk.de1chk1nd-lab.aws:5144"
