apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1-nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-v1-nginx
  template:
    metadata:
      labels:
        app: app-v1-nginx
    spec:
      containers:
      - name: app-v1-nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80
