apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: policy-web-nginx
  namespace: default
spec:
  waf:
    enable: true
    apPolicy: "secops/blocking-simple-web"
    securityLogs:
    - enable: true
      apLogConf : "secops/logconf-arcadia"
      logDest: "syslog:server=docker.blueprint-eu-west-1.aws:515"
