apiVersion: v1
kind: Service
metadata:
  name: app-v1-nginx-svc
  namespace: default
  labels:
    app: app-v1-nginx-svc
spec:
  ports:
  - name: app-v1-nginx-svc
    port: 8080
    protocol: TCP
    targetPort: 80
  type: ClusterIP
  selector:
    app: app-v1-nginx
