apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: virtualserver-web-nginx
  namespace: default
spec:
  host: simple-web-nginx.consol-blueprint.aws
  tls:
    secret: simple-web-nginx-cert
    redirect:
      enable: true
  policies:
  - name: policy-web-nginx
  upstreams:
  - name: web-nginx
    service: app-v1-nginx-svc
    port: 8080
  routes:
  - path: /
    action:
      pass: web-nginx
