apiVersion: v1
kind: Namespace
metadata:
  name: simple-web-nginx
  labels:
    name: simple-web-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1-nginx
  namespace: simple-web-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-v1-nginx
  template:
    metadata:
      labels:
        app: app-v1-nginx
    spec:
      containers:
      - name: app-v1-nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-v1-nginx-svc
  namespace: simple-web-nginx
  labels:
    app: app-v1-nginx-svc
spec:
  ports:
  - name: app-v1-nginx-svc
    port: 8080
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    app: app-v1-nginx
